spring:
  profiles:
    active: window-dev

---
server:
  port: 0

logging:
  level:
    yongs:
      temp: DEBUG
      
app:
  datasource:
    jdbc-url: jdbc:mariadb://localhost:3306/temp
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
    maximum-pool-size: 5
      
spring:
  profiles: window-dev
  application:
    name: yongs-user
  
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/